name: hafidomio_s_application2
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  google_maps_flutter: ^2.5.1
  staggered_grid_view_flutter: ^0.0.4
  intl: ^0.18.0
  path: ^1.8.0
  path_provider: ^2.0.1
  audioplayers: ^5.2.1
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0
  geocoding: ^2.1.1
  http: ^1.1.2
  uuid: ^4.3.3
  flutter_riverpod: ^2.4.9
  url_launcher: ^6.2.4
  record: ^5.0.4
  vibration: ^1.8.4
  cloud_firestore: ^4.15.5
  socket_io_client: ^2.0.3+1
  hooks_riverpod: ^2.4.10
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.4
  equatable: ^2.0.5
  sign_in_button: ^3.2.0
  permission_handler: ^11.3.0 
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Atkinson Hyperlegible
      fonts: 
        - asset: assets/fonts/AtkinsonHyperlegibleBold.ttf
          weight: 700
        - asset: assets/fonts/AtkinsonHyperlegibleRegular.ttf
          weight: 400
    - family: SF Pro Text
      fonts: 
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
