name: auricurrus_watch
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  intl: ^0.18.0
  socket_io_client: ^2.0.3+1
  provider: ^6.1.1
  vibration: ^1.8.4

dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Atkinson Hyperlegible
      fonts: 
        - asset: assets/fonts/AtkinsonHyperlegibleBold.ttf
          weight: 700
        - asset: assets/fonts/AtkinsonHyperlegibleRegular.ttf
          weight: 400
